// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9rbOuHmUpglQWpwHOwMygG4a4VONqSns',
    appId: '1:932300914263:web:56a7a4a6df1012575eed12',
    messagingSenderId: '932300914263',
    projectId: 'fruits-app-omar',
    authDomain: 'fruits-app-omar.firebaseapp.com',
    storageBucket: 'fruits-app-omar.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXKd2tkQAxMbAvHZVwMgNuG7A_DANaXCs',
    appId: '1:932300914263:android:9e26c49d4152401f5eed12',
    messagingSenderId: '932300914263',
    projectId: 'fruits-app-omar',
    storageBucket: 'fruits-app-omar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAreUva6DIrIHIeZEA2phCJ5MIltQ0rQFY',
    appId: '1:932300914263:ios:301d365fa0d7874c5eed12',
    messagingSenderId: '932300914263',
    projectId: 'fruits-app-omar',
    storageBucket: 'fruits-app-omar.firebasestorage.app',
    iosBundleId: 'com.example.fruitsECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAreUva6DIrIHIeZEA2phCJ5MIltQ0rQFY',
    appId: '1:932300914263:ios:301d365fa0d7874c5eed12',
    messagingSenderId: '932300914263',
    projectId: 'fruits-app-omar',
    storageBucket: 'fruits-app-omar.firebasestorage.app',
    iosBundleId: 'com.example.fruitsECommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9rbOuHmUpglQWpwHOwMygG4a4VONqSns',
    appId: '1:932300914263:web:75dc9ff5746e0bff5eed12',
    messagingSenderId: '932300914263',
    projectId: 'fruits-app-omar',
    authDomain: 'fruits-app-omar.firebaseapp.com',
    storageBucket: 'fruits-app-omar.firebasestorage.app',
  );
}
